apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
data:
  oauth2-proxy.cfg: |
    provider = "oidc"
    client_id = "OLmNQTGjwZaiTcuCWnSFu64l5B2pPCXp"
    client_secret = "zSXcJ1_gidUiG3Rlm3qp8gyQqdBqI2qxTLG72I3G7-IeROlrLN4PWQe4Z116betO"
    oidc_issuer_url = "https://dev-agov026zrx5oi6bw.eu.auth0.com/"
    #oidc_audience_claims = "https://dev-agov026zrx5oi6bw.eu.auth0.com/api/v2/"
    #oidc_audience_claims = "aud"
    oidc_extra_audiences = "https://dev-agov026zrx5oi6bw.eu.auth0.com/api/v2/"
    skip_jwt_bearer_tokens = true
    upstreams = "http://api-gateway.default.svc.cluster.local:80/"
    redirect_url = "http://oauth2-proxy.default.svc.cluster.local/oauth2/callback"
    set_authorization_header = true
    pass_authorization_header = true
    pass_access_token = true
    cookie_secret = "lGjkv9HcqqUXewomZfVhyOeQTqMxEjzR1BqExJHUFOU="
    email_domains = ["*"]
    #http_address = "0.0.0.0:4180"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --config=/etc/oauth2-proxy/oauth2-proxy.cfg
          ports:
            - containerPort: 4180
          volumeMounts:
            - name: config
              mountPath: /etc/oauth2-proxy
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: oauth2-proxy-config
