name: Deploy Exoscale SKS with OpenTofu

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Run OpenTofu
    runs-on: ubuntu-latest

    env:
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Init OpenTofu
        run: |
          tofu init

      - name: Validate OpenTofu config
        run: |
          cd infrastructure
          tofu plan

      - name: Apply OpenTofu configuration
        run: |
          cd infrastructure
          tofu apply -auto-approve
