name: Deploy Exoscale SKS with OpenTofu

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Run OpenTofu
    runs-on: ubuntu-latest

    env:
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Show OpenTofu version
        run: tofu version

      - name: Init OpenTofu
        run: |
          tofu init \
            -backend-config="access_key=${EXOSCALE_API_KEY}" \
            -backend-config="secret_key=${EXOSCALE_API_SECRET}"

      - name: Validate OpenTofu config
        run: |
          tofu plan

      - name: Apply OpenTofu configuration
        run: |
          tofu apply -auto-approve

      - name: Encode kubeconfig
        id: encode
        run: |
          content=$(cat kubeconfig | base64 | tr -d '\n')
          echo "::set-output name=content::$content"

      - name: Update GitHub Secret
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/EXOSCALE_KUBECONFIG \
            -d @- <<EOF
          {
            "encrypted_value": "${{ steps.encode.outputs.content }}",
            "key_id": "$(gh api repos/${{ github.repository }}/actions/secrets/public-key --jq .key_id)"
          }
          EOF
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
